spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql@2022
    url: jdbc:mysql://192.168.30.103:3306/test?rewriteBatchedStatements=true&serverTimezone=GMT%2B8
  jpa:
    generate-ddl: true
    database: mysql
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        format_sql: true
        order_inserts: true
worker-id: 2
leader-election:
  cron: "*/15 * * * * ?"
  timeout-sec: 20
  prefer-ips: 192.168.0,172.23

server:
  port: 8081