spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql@2022
    url: jdbc:mysql://localhost:3306/test
  jpa:
    generate-ddl: true
    database: mysql
    show-sql: true