spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql@2022
    url: jdbc:mysql://192.168.30.103:3306/test?rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
  jpa:
    generate-ddl: true
    database: mysql
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        format_sql: true
        order_inserts: true
  servlet:
    multipart:
      max-file-size: 10MB

worker-id: 2
leader-election:
  cron: "*/15 * * * * ?"
  timeout-sec: 20
  prefer-ips: 192.168.0,172.23

server:
  port: 8081
  servlet:
    context-path: /v1

minio:
  # 访问的url
  endpoint: http://192.168.0.136
  # API的端口
  port: 9001
  # 秘钥
  accessKey: YjKdaiJFzU06FkYQ
  secretKey: RBBzv3zVqwjJOed8iuBtPtOu6JEJXorS
  secure: false
  bucket-name: learning # 桶名 我这是给出了一个默认桶名
  image-size: 10485760 # 我在这里设定了 图片文件的最大大小
  file-size: 1073741824 # 此处是设定了文件的最大大小
